### ISSUE TITLE
.env file example

### ISSUE THREAD

**Issue by thedevdwarf** [jamesikjo/jamesjo.dev#1]
Could you add an example for env files in readme?

**Comment by jamesikjo** [comment]
Hi Osman, I added an [.env.example](https://github.com/jamesikjo/jamesjo.dev/blob/main/portfolio-next/.env.example). Let me know if there are any other questions or issues. It's very helpful to receive feedback from others!

**Comment by thedevdwarf** [comment]
Thanks for attentions
